# Generated by Django 5.0.6 on 2024-06-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Fee', models.CharField(max_length=50)),
                ('Order_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Order_Status', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=50)),
                ('Sub_Total', models.FloatField()),
            ],
            options={
                'db_table': 'tb_orders',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nme', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=70)),
                ('Price', models.IntegerField(default=0)),
                ('PictureUrl', models.CharField(default='', max_length=70)),
                ('IdBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('IdType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.type')),
            ],
            options={
                'db_table': 'tb_products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=70)),
                ('Price', models.IntegerField(default=0)),
                ('PictureUrl', models.CharField(default='', max_length=70)),
                ('IdOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders')),
                ('IdProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'tb_orderitem',
            },
        ),
    ]
