# Generated by Django 5.0.6 on 2024-06-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Delivery_Fee',
            field=models.CharField(max_length=51),
        ),
    ]
