# Generated by Django 5.0.6 on 2024-06-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='Nme',
        ),
        migrations.AddField(
            model_name='type',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
