# Generated by Django 5.0.6 on 2024-06-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_type_nme_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
