# Generated by Django 5.0.6 on 2024-06-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_brand_name_alter_orders_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Sub_Total',
        ),
    ]
