# Generated by Django 5.0.6 on 2024-06-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_orderitem_description_remove_orderitem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='IdProductsOrder',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='IdProductsOrder',
            field=models.ManyToManyField(to='store.productsorder'),
        ),
    ]
