# Generated by Django 5.0.6 on 2024-06-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_idproductsorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
    ]
