# Generated by Django 5.0.6 on 2024-06-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orders_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Zipcode',
            field=models.CharField(max_length=70),
        ),
    ]
