# Generated by Django 5.0.6 on 2024-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_productsorder_productcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='StatusOrderDetail',
            field=models.CharField(default='Llego el correo , se valido', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
