# Generated by Django 5.0.6 on 2024-06-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_iduser_alter_orderitem_idorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='IdOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='IdProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
