# Generated by Django 5.0.6 on 2024-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_statusorderdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
