# Generated by Django 5.0.6 on 2024-06-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorder',
            name='Amount',
            field=models.IntegerField(default=1),
        ),
    ]
